// undefined + undefined = NaN
// undefined + 1(any number) = NaN
// undefined + NaN = NaN
// 1(any number +ve or -ve) + NaN = NaN
// NaN + (-1) = NaN
// NaN + [] = 'NaN'
//  NaN + {} = 'NaN[object Object]'
// NaN + "1234" = 'NaN1234'
// undefined + null = NaN
// 0(any number) + null = 0(any number)
// null + null = 0
// null + NaN = NaN
// typeof NaN = 'number'
// typeof null = 'object'
// typeof undefined = 'undefined'
// typeof [] = 'object'
// typeof {} = 'object'
// typeof " "  = 'string'
// typeof function name(params) { } = 'function'
